// <auto-generated />
namespace Uoko.FireProj.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class resourceserverrefined : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resourceserverrefined));
        
        string IMigrationMetadata.Id
        {
            get { return "201603031412301_resource-server-refined"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
