// <auto-generated />
namespace Uoko.FireProj.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateResourceInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateResourceInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201601250905453_updateResourceInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
