// <auto-generated />
namespace Uoko.FireProj.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addOnlineTaskInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addOnlineTaskInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201603040634395_addOnlineTaskInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
